import requests

from bs4 import BeautifulSoup
from typing import Optional


# Generated by DeepSeek, you can help improve it by committing PRs!
def parse_url_info(url: str, locale: Optional[str] = None):
    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36 Edg/133.0.0.0'
        }
        if locale is not None and isinstance(locale, str):
            headers['Accept-Language'] = locale
        response = requests.get(url, headers=headers, timeout=10)
        response.encoding = 'utf-8'
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')
        
        title = soup.title.string.strip() if soup.title else '未找到标题'
        
        summary = ''
        meta_desc = soup.find('meta', attrs={'name': 'description', 'lang': 'zh-CN'})
        if not meta_desc:
            meta_desc = soup.find('meta', attrs={'name': 'description'})
        if meta_desc and meta_desc.get('content'):
            summary = meta_desc.get('content').strip()
        else:
            paragraphs = soup.find_all('p')
            chinese_text = []
            for p in paragraphs[:5]:
                text = p.get_text().strip()
                if any('\u4e00' <= c <= '\u9fff' for c in text):
                    chinese_text.append(text)
                    if len(chinese_text) >= 2:
                        break
            summary = ' '.join(chinese_text)[:200] + '...' if chinese_text else '未找到中文摘要'
        
        return {'title': title, 'summary': summary}
    
    except requests.exceptions.RequestException as e:
        return {'error': f'Error request: {str(e)}'}
    except Exception as e:
        return {'error': f'Error parse: {str(e)}'}